const express = require('express');
const router = express.Router();
const bodyParser = require('body-parser').json();
const Player = require('../models/player');

router
    .get('/', (req, res, next) => {
        // by itself, {} will return all Players
      const query = {};

        // if we have a team to query on, add that property
        // (which will filter on players that have that team)
        // e.g. "?Cubs"
      if(req.query.team) query.team = req.query.team;

      Player.find(query)
            .then(players => res.send(players ))
            .catch(next);
    })

    //id's being those long-ass id's generated by Mongo
    .get('/:id', (req, res, next) => {
      Player.findById(req.params.id)
            .then(player => res.send(player ))
            .catch(next);
    })

    .delete('/:id', (req, res, next) => {
      Player.removeById(req.params.id)
            .then(deleted => res.send(deleted ))
            .catch(next);
    })
    //JSON data in non-array format
    .post('/', bodyParser, (req, res, next) => {
      new Player(req.body).save()
            .then(saved => res.send(saved ))
            .catch(next);
    })

    .put('/:id', bodyParser, (req, res, next) => {
      Player.findByIdAndUpdate(req.params.id, req.body)
            .then(saved => res.send(saved))
            .catch(next);
    });

module.exports = router;