const express = require('express');
const router = express.Router();
const bodyParser = require('body-parser').json();
const Team = require('../models/team');

router
    .get('/', (req, res, next) => {
        // by itself, {} will return all Teams
      const query = {};

        // if we have a league to query on, add that property
        // (which will filter on teams that have that league)
        // e.g. "?American"
      if(req.query.league) query.league = req.query.league;

      Team.find(query)
            .then(teams => res.send(teams ))
            .catch(next);
    })

    //id's being those long-ass id's generated by Mongo
    .get('/:id', (req, res, next) => {
      Team.findById(req.params.id)
            .then(team => res.send(team ))
            .catch(next);
    })

    .delete('/:id', (req, res, next) => {
      Team.removeById(req.params.id)
            .then(deleted => res.send(deleted ))
            .catch(next);
    })
    //JSON data in non-array format
    .post('/', bodyParser, (req, res, next) => {
      new Team(req.body).save()
            .then(saved => res.send(saved ))
            .catch(next);
    })

    .put('/:id', bodyParser, (req, res, next) => {
      Team.findByIdAndUpdate(req.params.id, req.body)
            .then(saved => res.send(saved))
            .catch(next);
    });

module.exports = router;